linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_escaping_inner_quotes
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_void_async
    - await_only_futures
    - constant_identifier_names
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_contains
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_spread_collections
    - prefer_null_aware_method_calls
    - sized_box_for_whitespace
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_unnamed_constructors_first
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_named_constants
    - void_checks
    - avoid_relative_lib_imports
