# DO NOT CHANGE THE NAME (edemand_partner),
#IF YOU WANT TO CHANGE THE APP NAME THEN YOU HAVE TO CHANGE THE EACH IMPORT STATEMENT IN THE CODE
#THIS NAME WILL NOT IMPACT IN YOUR APP, SO ITS NOT MANDATORY TO CHANGE IT
name: edemand_partner
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version: 4.0.0+1
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  intl: any
  image_picker: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.1.1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  shimmer: ^3.0.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.0.4
  fl_chart: ^0.70.2
  cached_network_image: ^3.2.3
  rive: ^0.13.5
  version: ^3.0.2
  url_launcher: ^6.1.7
  package_info_plus: ^8.0.0
  firebase_auth: ^5.1.4
  pinput: ^5.0.0
  google_maps_flutter: ^2.2.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  change_app_package_name: ^1.1.0
  path_drawing: ^1.0.1
  file_picker: ^8.0.3
  video_player: ^2.6.1
  mime: ^2.0.0
  http_parser: ^4.0.2
  path: ^1.8.2
  quick_actions: ^1.0.2
  awesome_notifications: ^0.10.1
  open_filex: ^4.3.2
  html_editor_enhanced: ^2.5.1
  flutter_widget_from_html: ^0.16.0
  razorpay_flutter: ^1.3.5
  flutter_stripe: ^11.0.0
  webview_flutter: ^4.0.7
  lottie: ^3.0.0
  readmore: ^3.0.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  any_link_preview:
  google_mobile_ads: ^5.1.0
  easy_stepper: ^0.8.5+1
  toastification: ^3.0.2
  vibration: ^3.1.2
  # shared_preferences: ^2.5.1

dependency_overrides:
  intl: ^0.17.0
  webview_flutter_android: 4.0.1 #3.16.1
#added flutter_inappwebview_ios dependency to fix the issue while running the app on ios
  flutter_inappwebview_ios:
    git:
      url: https://github.com/IncM/flutter_inappwebview
      path: flutter_inappwebview_ios
      ref: cbc214c7b2cf5fd7996ff2e9e25d203946b74bc3
dev_dependencies:
  rename: ^3.0.2
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/languages/
    - assets/mapTheme/
    - assets/animation/
    - assets/images/flags/
    - assets/countryCodes/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100
